default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        # Exclude Markdown files because `  ` at the end of a line is a valid
        # syntax to notify a line break.
        # See https://github.com/pre-commit/pre-commit-hooks/issues/57
        exclude: ".*\\.md"
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
