name: lint

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
